# vim: ft=dockerfile:
# Derived from official mysql image (our base image)
FROM mysql
# Add a database
ENV MYSQL_DATABASE symp_internal
# exec all scripts from sql-startup on database's startup
COPY ./sql-startup/ /docker-entrypoint-initdb.d/
